// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Match is the predicate function for match builders.
type Match func(*sql.Selector)

// Participation is the predicate function for participation builders.
type Participation func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
