// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/horiyuko0512/soccer-community/ent/user"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// NickName holds the value of the "nickName" field.
	NickName string `json:"nickName,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// PasswordHash holds the value of the "password_hash" field.
	PasswordHash string `json:"password_hash,omitempty"`
	// Introduction holds the value of the "introduction" field.
	Introduction string `json:"introduction,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Matches holds the value of the matches edge.
	Matches []*Match `json:"matches,omitempty"`
	// UserParticipation holds the value of the user_participation edge.
	UserParticipation []*Participation `json:"user_participation,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int

	namedMatches           map[string][]*Match
	namedUserParticipation map[string][]*Participation
}

// MatchesOrErr returns the Matches value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) MatchesOrErr() ([]*Match, error) {
	if e.loadedTypes[0] {
		return e.Matches, nil
	}
	return nil, &NotLoadedError{edge: "matches"}
}

// UserParticipationOrErr returns the UserParticipation value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) UserParticipationOrErr() ([]*Participation, error) {
	if e.loadedTypes[1] {
		return e.UserParticipation, nil
	}
	return nil, &NotLoadedError{edge: "user_participation"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldNickName, user.FieldEmail, user.FieldPasswordHash, user.FieldIntroduction:
			values[i] = new(sql.NullString)
		case user.FieldCreatedAt, user.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case user.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (u *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				u.ID = *value
			}
		case user.FieldNickName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nickName", values[i])
			} else if value.Valid {
				u.NickName = value.String
			}
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				u.Email = value.String
			}
		case user.FieldPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_hash", values[i])
			} else if value.Valid {
				u.PasswordHash = value.String
			}
		case user.FieldIntroduction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field introduction", values[i])
			} else if value.Valid {
				u.Introduction = value.String
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				u.CreatedAt = value.Time
			}
		case user.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				u.UpdatedAt = value.Time
			}
		default:
			u.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (u *User) Value(name string) (ent.Value, error) {
	return u.selectValues.Get(name)
}

// QueryMatches queries the "matches" edge of the User entity.
func (u *User) QueryMatches() *MatchQuery {
	return NewUserClient(u.config).QueryMatches(u)
}

// QueryUserParticipation queries the "user_participation" edge of the User entity.
func (u *User) QueryUserParticipation() *ParticipationQuery {
	return NewUserClient(u.config).QueryUserParticipation(u)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (u *User) Update() *UserUpdateOne {
	return NewUserClient(u.config).UpdateOne(u)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (u *User) Unwrap() *User {
	_tx, ok := u.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	u.config.driver = _tx.drv
	return u
}

// String implements the fmt.Stringer.
func (u *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", u.ID))
	builder.WriteString("nickName=")
	builder.WriteString(u.NickName)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(u.Email)
	builder.WriteString(", ")
	builder.WriteString("password_hash=")
	builder.WriteString(u.PasswordHash)
	builder.WriteString(", ")
	builder.WriteString("introduction=")
	builder.WriteString(u.Introduction)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(u.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(u.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// NamedMatches returns the Matches named value or an error if the edge was not
// loaded in eager-loading with this name.
func (u *User) NamedMatches(name string) ([]*Match, error) {
	if u.Edges.namedMatches == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := u.Edges.namedMatches[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (u *User) appendNamedMatches(name string, edges ...*Match) {
	if u.Edges.namedMatches == nil {
		u.Edges.namedMatches = make(map[string][]*Match)
	}
	if len(edges) == 0 {
		u.Edges.namedMatches[name] = []*Match{}
	} else {
		u.Edges.namedMatches[name] = append(u.Edges.namedMatches[name], edges...)
	}
}

// NamedUserParticipation returns the UserParticipation named value or an error if the edge was not
// loaded in eager-loading with this name.
func (u *User) NamedUserParticipation(name string) ([]*Participation, error) {
	if u.Edges.namedUserParticipation == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := u.Edges.namedUserParticipation[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (u *User) appendNamedUserParticipation(name string, edges ...*Participation) {
	if u.Edges.namedUserParticipation == nil {
		u.Edges.namedUserParticipation = make(map[string][]*Participation)
	}
	if len(edges) == 0 {
		u.Edges.namedUserParticipation[name] = []*Participation{}
	} else {
		u.Edges.namedUserParticipation[name] = append(u.Edges.namedUserParticipation[name], edges...)
	}
}

// Users is a parsable slice of User.
type Users []*User
